### PR TITLE
Feat/inventory toolbar interface

### PR DESCRIPTION
**Pull request by kloppz**
Hi, new feature!
I create a interface to inventory toolbar
Captura de pantalla 2019-08-12 a las 22 17 31

If u pick 1-9 in keyboard its active

in next feature i create interface of experience and health

### CODE REVIEW

**Comment by ian13456** [comment]
This is awesome! I've actually made an inventory a few months ago before I rewrote the entire game structure. You can check it out [here](https://github.com/ian13456/mc.js/tree/feat/terrain/client/src/components/Game/Minecraft/App/Player/Inventory).

I'll take a look at this pull request very soon and maybe make some minor changes, and then I'll merge it. Minor changes include using a prewritten function in `Keyboard.js` called [`registerIndexedGroup`](https://github.com/ian13456/mc.js/blob/4cc0d0218fe913b468c572b95db20395515fc627/core/lib/userInputs/keyboard.js#L114) and moving an inventory to `player.js` instead of `world.js` since that makes more sense.

**Comment by kloppz** [comment]
Im refactor with your requisites! 
in next PR i implmeente your Inventory scripts to equal in this feature, we can finish this when u want, this its only interface.

**Comment by kloppz** [comment]
Hi again!
i see your code in feat/terrain and i insert and refactor basic
i insert hearts calculates in base of health.
mid heart = 1 hp,
1 heart = 2hp
10 hearts(full) = 20hp
10 hearts + 10 armor = 40hp

say me feedback about this!

**Comment by kloppz** [comment]
Hi! im on fire and i create armor and hungry interface too!
Captura de pantalla 2019-08-13 a las 22 22 43

for now i dont create in water status, im pref first get info from database

Give me feedback!

**Comment by ian13456** [comment]
Oh wow! This is awesome! I'll take a look at it and I'll confirm the merge. I believe hunger/armor/health will come into use after implementing something like a `player's state` on the backend side. Thanks a lot anyways!

**Comment by ian13456** [comment]
Looks good!

**Pull request merged**
