### PR TITLE
add sneaking camera position

### PR DESCRIPTION
**Pull request by kloppz**
Hello!
I'm from spain and i try to collaborate to your repo!
I'm start with player sneaking mode, but i only set camera, in next i set velocity of movements.
Give me Feedback!
Thank you!

### CODE REVIEW

**Comment by ian13456** [comment]
Thanks a lot! I will merge this feature to master once you're done!
I quickly went through your code and I suggest instead of using a fixed constant (-10) of how low the camera changes, I recommend adjusting the camera position according to the player's height, which may be something multiplied by `Config.player.aabb.eye2toe + Config.player.aabb.eye2top`!
Again, it would be awesome if you can work on sneak mode!

**Comment by ian13456** [comment]
Just a quick note that the aabb values (_eye2toe_ and _eye2top_) are in units of **blocks**. In other words `eye2top = 0.2` means the distance from the camera to the top of a player is equal to `0.2 * block_dimension`. Block dimension can be found in `Config.block.dimension`. So, the height difference should be something like `SHIFT_CONSTANT *  HEIGHT * DIMENSION`.

Another thing I'd like to say is that instead of using `Config.something.something` directly, for code consistency, constants should be extracted from `Config` in the top lines of any file in caps as such:
```javascript
const DIMENSION = Config.block.dimension
```

Good luck!

**Comment by kloppz** [comment]
Thanks to comments!
Question, eye2top and eye2toe its height player?  and not its all players same height? why in diferents worlds its diferent in relation with block dimension?
all blocks have same dimension?
Thank you!

**Comment by kloppz** [comment]
Im search information in minecraft and i see this:
https://minecraft.gamepedia.com/Player#Sneaking
config now: 
width: 1.5 vs minecraft: 1.6
height: 1.8 vs 1.8
sneaking: ?? vs minecraft 1.5/1.65

If you want we can take the same, take 1.65 in config

**Comment by ian13456** [comment]
So `eye2top` and `eye2toe` are used for players' collision, and all players have the same height in every world. I extracted them out so that in the future if a player changes their height (for example, morphing into other forms), it'd be easier to determine where the camera is and how the collision of the player should be calculated. Also, all cubical blocks have the same dimensions in all worlds. 👍 👍

**Comment by kloppz** [comment]
Oh, rlly nice feature!
ok,  in official minecraft its 15~20% of height, we set same height relation with block?
https://minecraft.gamepedia.com/Player#Sneaking

**Comment by ian13456** [comment]
Sure! So the camera height adjustment should be something like this:
```javascript
// config.js
const Config = {
   ... 
   player: {
      ...
      aabb: {
      ...
      sneakDifference: 0.2,
      ...
      },
   },
   ...
}

// controls.js
const SNEAK_DIFF = Config.player.aabb.sneakDifference
const PLAYER_HEIGHT = EYE_2_TOE + EYE_2_TOP
const CAM_SNEAK_DIFF = SNEAK_DIFF * PLAYER_HEIGHT * DIMENSION

...

camera.position.y -= CAM_SNEAK_DIFF
```

Good luck again!

**Comment by kloppz** [comment]
nice! this is my ideal! thanks!
If i set camera.position.y -= CAM_SNEAK_DIFF when pressed key not stop to substract values, we need fixed substract value only 1 time.

**Comment by ian13456** [comment]
Okok great! By the way can you change your commit messages according to [convention commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)? This is mentioned in CONTRIBUTING.md👍👍

**Comment by kloppz** [comment]
i finished feature,  say me more if u need in this feature!

**Comment by ian13456** [comment]
Awesome! I'm making some minor bug fixes to this pull request such as when you shift, the water texture seems to glitch out. Also, you know how when you sneak in Minecraft, you won't fall off the platform you're standing on? It'd be great if that's implemented. I'll merge this pull request once that's done! :+1:

**Comment by ian13456** [comment]
Using [TweenJS](https://github.com/tweenjs/tween.js/) to transition camera position too.

**Comment by ian13456** [comment]
I added a smoother sneaking transition and rebased to master :+1: :+1: Looking good!

**Comment by kloppz** [comment]
Rlly nice! u can merge with master if u want!

**Comment by ian13456** [comment]
Great job!

**Pull request merged**
