### PR TITLE
Fix exceptions if user does not have settings yet

### PR DESCRIPTION
**Pull request by Fi1osof**

### CODE REVIEW

**Comment by ian13456** [comment]
Isn't `settings` created by default in the `signup` resolver?

**Comment by Fi1osof** [comment]
I do integration with exists prisma-project where existsing users have not settings yet.

**Comment by ian13456** [comment]
Hmm...
Wouldn’t a `yarn run reset` do the trick?

**Comment by Fi1osof** [comment]
Deploy will rejected with message 
```
Errors:

  User
    ✖ You are making a field required, but there are already nodes that would violate that constraint.

Deployment canceled. Please fix the above errors to continue deploying.

```
I already have user records without setting.

**Comment by ian13456** [comment]
This is why `yarn run reset` resets the database and removes all existing data by running `prisma delete -f`.

**Comment by Fi1osof** [comment]
I do not want to delete my users from working site:) 
https://prisma-cms.com/

**Comment by balta-z-r** [comment]
Sorry, this pull request isn't specifically for our project, however. We appreciate your involvement

**Comment by ian13456** [comment]
You can also alter the prisma docker configs for your local development. This way you can have two databases 👍👍👍

**Comment by Fi1osof** [comment]
> Sorry, this pull request isn't specifically for our project. However, we appreciate your involvement

Prisma.io, apollo-client, graphql, and many other isn't specifically for your project too. I do not think for own project only. I mean compatibility. I completed integration of my site with mc.js. https://minecraft.prisma-cms.com/ And any [users](https://prisma-cms.com/people) from main site can now login in game ([users who joined game](https://prisma-cms.com/people?filters=%7B%22PrismaProjects_some%22%3A%7B%22domain%22%3A%22minecraft.prisma-cms.com%22%7D%7D)). And i say: this is not been easy. 

Any way: thanks a lot!

**Comment by ian13456** [comment]
I think what @balta-z-r meant by **specifically** is that the changes this pull request makes are not necessary for this project if it has its own database. Personally I wouldn't suggest using the same database for all projects since the schema's may differ dramatically from project to project. However it's totally fine if you tweak your local copy of this project to fit your existing website! 👍👍

**Comment by Fi1osof** [comment]
@ian13456 It's necessary for this project. Prisma.io allow to upgrade/alter database often. Today someone starts new project with users and topics. Tomorrow  add another graphql types. After this they find mc.js, liked this, want to add in own project and can't do this cause users already exists.
I had to add createSetting mutation: https://github.com/Fi1osof/mc.js/commit/a35715563bf12dbe6ada9a82c220484781eedbcc
and [fix ws endpoints in too places](https://github.com/Fi1osof/mc.js/commit/0f5ddeb41323e7f3668f5e2c50164384830014bc).
Now it's dedicated project. In my [prisma-cms](https://github.com/prisma-cms?) i'm trying to create separated [modules](https://github.com/prisma-cms/module-boilerplate) (for server) and [components](https://github.com/prisma-cms/component-boilerplate) (for front) to be able to create different projects with different functionaly (it's just for examply, not only i do like this:))).
Here i add new mc.js module: https://github.com/prisma-cms/prisma-cms.com/blob/mc.js/src/server/modules/index.mjs#L52 and now having complete API with mc.js https://api.prisma-cms.com/

**Pull request closed without merging**
