### PR TITLE
feat: get and update player status in database

### PR DESCRIPTION
**Pull request by kloppz**
hi!
other feature, i get and update health, armor and hunger from database

in next i create feature to system health/hunger increment/decrement

i modify graphql schema, you need run yarn run prisma:deploy --force

### CODE REVIEW

**Comment by kloppz** [comment]
im auto health and auto hunger.

in config we can set timing, now in 5 minutes is died.

give me feedback!

**Comment by ian13456** [comment]
I'll check this out right now!

**Comment by kloppz** [comment]
Question, we have status.js too, and playerState, if we move setters in status.js and only interface in playerState.js?
Give me feedback

**Comment by ian13456** [comment]
Ohhhh!! That is a fantastic idea! Should I do it or...?

**Comment by ian13456** [comment]
This pull request is looking really promising!

**Comment by kloppz** [comment]
I refactor to this change!

**Comment by kloppz** [comment]
im finish to refactor! now its better to update status!

**Comment by ian13456** [comment]
Great job! This is awesome!

**Pull request merged**
