### PR TITLE
feat: add third person camera

### PR DESCRIPTION
**Pull request by kloppz**
Added key F5 to switch first person/third person
in nexts features we need set skin to show in third person
with skin we can show distance to third person correctly

### CODE REVIEW

**Comment by ian13456** [comment]
Awesome!!! Check out [playerObject.js](https://github.com/ian13456/mc.js/blob/master/core/lib/playerObject/playerObject.js) which is used in the branch `feat/multiplayer` to render player mesh. Animations and such will be added in the future. Also, I've seen on the internet that it's not that good to override f5 since f5 is a built-in key for most browsers to refresh the page. I would say use other keys for now.

**Comment by ian13456** [comment]
Sorry, I linked the wrong file. [This](https://github.com/ian13456/mc.js/blob/master/core/modules/managers/playersManager/playerObject.js) should be the actual playerObject.js. I'll make changes to the file location soon.

**Comment by kloppz** [comment]
Hi! im see file but i dont see where you init player skin,
we set player skin when create a Player? not its better set in [player.js](https://github.com/ian13456/mc.js/blob/feat/multiplayer/core/modules/app/player/player.js)
other option its if when multiplayer feature all players have skin, its not necessary my implementation.

Say me about this, thanks!

**Comment by ian13456** [comment]
You can think of the `PlayerObject` class as the control of a player's mesh. It extends `THREE.Group` so it has attributes such as `position` and `rotation`.

Currently `PlayerObject` is only used in [`playerClient.js`](https://github.com/ian13456/mc.js/blob/master/core/modules/managers/playersManager/playerClient.js) to control other player's mesh. (even though the feature still only exists in branch [`feat/multiplayer`](https://github.com/ian13456/mc.js/tree/feat/multiplayer))

As you can see in [`playerClient.js`](https://github.com/ian13456/mc.js/blob/master/core/modules/managers/playersManager/playerClient.js), by initiating an instance of `PlayerObject` and passing in a skin, position and direction, you can control the skin mesh easily by tweening the mesh.

So what I would say to render a player's own mesh, you initiate a `PlayerObject` inside of `player.js`, and control the mesh according to the player's movements...?

Good luck!

**Comment by kloppz** [comment]
close this to merge structures and i create new PR to show skin ;)

**Comment by ian13456** [comment]
The latest PR seems to have conflicts with this one. I’ll merge once it’s fixed!

**Comment by kloppz** [comment]
now its ok!

**Pull request merged**
